version: '3.9'

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  api-backend:
    image: krios2146/animal-chipping-api:api-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/animal-chipization
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
