name: Rebuild app

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client and sshpass
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass
      - name: Connect to a host
        run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -t root@78.153.130.215
      - name: Stop the app
        run: |
          cd animal-chipping-api && 
          docker-compose down
      - name: Delete old Docker images
        run: docker rmi krios2146/animal-chipping-api:api-frontend krios2146/animal-chipping-api:api-backend -f
      - name: Up the app with new images
        run: docker-compose up
