name: Rebuild app

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands via SSH
        uses: Flaavius/ssh-commands@1.0
        with:
          command: |
            cd animal-chipping-api && 
            docker-compose down
            docker rmi krios2146/animal-chipping-api:api-frontend krios2146/animal-chipping-api:api-backend -f
            docker-compose up
          host: 78.153.130.215
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
